//===- SAFECode.h - Common definitions of SAFECode Compiler ------------------//
// 
//                          The SAFECode Compiler 
//
// This file was developed by the LLVM research group and is distributed under
// the University of Illinois Open Source License. See LICENSE.TXT for details.
// 
//===----------------------------------------------------------------------===//
//
// This file defines all common configuration used by SAFECode
// compiler. It also includes the config.h generated by the configure
// script. Technically, all files should include this header to
// guarantee that the build system handles all dependencies correctly.
//
//===----------------------------------------------------------------------===//

#ifndef _SAFECODE_H_
#define _SAFECODE_H_

#include "safecode/Config/config.h"

#define NAMESPACE_SC safecode
#define NAMESPACE_SC_BEGIN namespace safecode {
#define NAMESPACE_SC_END }

#endif
