
LEVEL = ../../../..

BUILD_ARCHIVE := 1
LIBRARYNAME=addchecks

SOURCES = GEPChecks.cpp \
          CFIChecks.cpp \
          InvalidFreeChecks.cpp \
          RegisterBounds.cpp \
          RegisterRuntimeInitializer.cpp \
          RegisterStackObjPass.cpp \
          CompleteChecks.cpp \
          Terminate.cpp \
          #AlignmentChecks.cpp \
          #MonotonicLoopOpt.cpp \
          #ClearCheckAttributes.cpp \
          #insert.cpp

include $(LEVEL)/projects/safecode/Makefile.common

