##===- lib/FormatStrings/Makefile -----------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../../../..

#
# Give the name of a library.  This will build a dynamic version.
#
LIBRARYNAME=formatstrings

#
# Include projects/safecode/Makefile.common so we know what to do.
#
include $(LEVEL)/projects/safecode/Makefile.common

