#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
#PARALLEL_DIRS=SafePoolAllocator BoundsCheckAllocator KernelSafePoolAllocator KPoolCheck UserPoolSystem
#PARALLEL_DIRS=BitmapPoolAllocator DebugRuntime SVA
PARALLEL_DIRS=BitmapPoolAllocator DebugRuntime SVA BBRuntime FloatConversion

include $(LEVEL)/Makefile.common
