##===- runtime/Makefile ------------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL = ../../..

PARALLEL_DIRS  := BitmapPoolAllocator DebugRuntime FloatConversion SoftBoundRuntime BBRuntime
#PARALLEL_DIRS  := BitmapPoolAllocator DebugRuntime FloatConversion SoftBoundRuntime

include $(LEVEL)/Makefile.common
